# Welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]])


In [3]:
myarr

array([[ 3,  6, 32,  7]])

In [4]:
myarr[0,1]

6

In [5]:
 myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr = np.array([[3,6,32,7]],np.int64)


In [8]:
myarr.dtype

dtype('int64')

# 5 general mechanism for creating arrays:



1.Conversion from other python structure (eg: lists and tuples)
2.Intrinsic numpy array creation objects(eg: Arrange,ones,zeros etc)
3.Reading arrays from disk, either from strandard or custom formats 
4.Creating arrys from raw bytes through the use of strings or buffers
5.use of special library functions(eg.random)

** Array Creation**

In [9]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])


In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({34,24,33})

array({24, 33, 34}, dtype=object)

In [15]:
zeros = np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
rng = np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lspace = np.linspace(1,5,12)

In [20]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [21]:
lspace1 = np.linspace(1,50,5)

In [22]:
lspace1

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [23]:
emp = np.empty((4,6))

In [24]:
emp

array([[6.23042070e-307, 1.15710088e-306, 1.78020169e-306,
        8.45593934e-307, 1.24610383e-306, 1.69118108e-306],
       [8.06632139e-308, 1.20160711e-306, 1.69119330e-306,
        1.60219035e-306, 1.11260619e-306, 1.00132398e-307],
       [1.00132483e-307, 1.42410838e-306, 1.33508336e-307,
        1.02360392e-306, 9.79107193e-307, 7.56599807e-307],
       [1.42420345e-306, 6.89807188e-307, 1.20160711e-306,
        1.69119330e-306, 1.78022206e-306, 1.78022206e-306]])

In [25]:
emp_like = np.empty_like(lspace1)

In [26]:
emp_like

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [27]:
ide = np.identity(45)

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr = arr.reshape(3,33)

In [34]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.shape

(3, 33)

In [37]:
x = [[1,2,3],[4,5,6],[7,8,1]]

In [38]:
ar = np.array(x)

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1]])

In [40]:
ar.sum(axis= 0)

array([12, 15, 10])

In [41]:
ar.sum(axis =1)

array([ 6, 15, 16])

In [42]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 1]])

In [43]:
ar.flat

In [44]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
1


In [45]:
ar.ndim

2

In [46]:
ar.size
#elemts size

9

In [47]:
#elemts takes total btyes
ar.nbytes

36

In [48]:
one = np.array([1,2,4,6,5,333,7])


In [49]:
# tells about max elemts index position
one.argmax()


5

In [50]:
#tells aboout lowers elemts index position 
one.argmin()

0

In [51]:
# tells about lower to greater ind4ex numbers
one.argsort()

array([0, 1, 2, 4, 3, 6, 5], dtype=int64)

In [52]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1]])

In [53]:
ar.argmin()

0

In [54]:
ar.argmax()

7

In [55]:
ar.argmax(axis = 0)

array([2, 2, 1], dtype=int64)

In [56]:
ar.argmax(axis = 1)

array([2, 2, 1], dtype=int64)

In [57]:
ar.argsort(axis =1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [58]:
ar.argsort(axis =0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]], dtype=int64)

In [59]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 1])

In [60]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1]])

In [61]:
 ar2 = np.array([[1,2,1],
                [4,0,6],
                [8,1,0]])

In [62]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  1]])

In [63]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [64]:
ar-ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  7,  1]])

In [65]:
ar2/ar

array([[1.        , 1.        , 0.33333333],
       [1.        , 0.        , 1.        ],
       [1.14285714, 0.125     , 0.        ]])

In [66]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 1.        ]])

In [67]:
ar.sum()

37

In [68]:
ar.max()

8

In [69]:
ar.min()

1

In [70]:
##elemts find in array


In [71]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1]])

In [72]:
np.where(ar>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [73]:
type(np.where(ar>5))

tuple

In [74]:
np.count_nonzero(ar)

9

In [75]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [76]:
ar[1,2]=0

In [77]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [78]:
import sys

In [79]:
py_ar = [0,4,55,2]

In [80]:
np_ar =np.array(py_ar)

In [81]:
sys.getsizeof(1)*len(py_ar)

112

In [82]:
np_ar.itemsize * np_ar.size

16

In [83]:
np_ar.tolist()

[0, 4, 55, 2]

In [84]:
# starting again with all codes


In [85]:
arr1 = np.ones((3,3))

In [86]:
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
arr1.itemsize

8

In [88]:
arr2 = np.eye(3)

In [89]:
print(arr2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Numpy Random Numbers


In [90]:
#1. 

In [91]:
arr = np.random.rand(5)

In [92]:
arr

array([0.83734704, 0.50601352, 0.87146516, 0.8462179 , 0.74468647])

In [93]:
print(np.random.rand(10,2))

[[0.36780323 0.81987219]
 [0.82590831 0.28679124]
 [0.7922007  0.16818483]
 [0.2687304  0.10119411]
 [0.3771827  0.07558991]
 [0.48542098 0.80365863]
 [0.86398725 0.06264453]
 [0.01231392 0.77397543]
 [0.06089376 0.078422  ]
 [0.02457276 0.32148382]]


In [94]:
# taking one intergr between 0 to 9 
print(np.random.randint(10))

7


In [95]:
print(np.random.randint(10,size = (5,4)))

[[9 9 0 5]
 [7 3 4 7]
 [0 6 8 2]
 [4 8 2 2]
 [7 1 1 2]]


In [96]:
print(np.random.randint(10,50,size = (5,4)))

[[29 47 46 41]
 [49 26 37 22]
 [10 35 27 28]
 [20 36 33 20]
 [42 44 33 24]]


In [97]:
print(np.random.uniform(10))

8.311941982471431


In [98]:
print(np.random.uniform(10,size = (5,4)))

[[4.59771296 1.32301921 5.82621363 2.8336068 ]
 [7.60942389 7.37586897 9.27481399 3.9919913 ]
 [3.05778153 4.13584908 3.56021102 2.98621129]
 [7.07899947 7.60447385 6.09885154 2.27653666]
 [7.8053217  6.85574245 7.98058483 4.95227072]]


In [99]:
print(np.random.uniform(10,50,size = (5,4)))

[[32.69977022 49.621243   26.48337646 30.57975431]
 [35.95952236 47.98095108 19.38798756 31.445688  ]
 [19.13936533 18.97567248 16.86540988 19.24175043]
 [12.62417543 18.95894114 26.7654323  44.54818502]
 [21.63129295 28.31925855 25.51331027 37.85904657]]


# Numpy Indexing


In [100]:
arr = 3*np.arange(10)

In [101]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [102]:
arr[2]

6

In [103]:
arr[9]

27

In [104]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1,0])

4


In [105]:
arr[0,1]=32
arr

array([[ 1, 32,  3],
       [ 4,  5,  6]])

# Numpy slicing


In [106]:
arr = np.arange(10)

In [107]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
arr[::2]

array([0, 2, 4, 6, 8])

In [109]:
print(arr[1:4])
print(arr[0:-4])

[1 2 3]
[0 1 2 3 4 5]


# Maths in Numpy

In [110]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[22,33,1],[66,54,73]])
print(np.add(a,b))

[[23 35  4]
 [70 59 79]]


In [111]:
np.subtract(a,b)

array([[-21, -31,   2],
       [-62, -49, -67]])

In [112]:
np.multiply(a,b)

array([[ 22,  66,   3],
       [264, 270, 438]])

In [113]:
np.divide(a,b)

array([[0.04545455, 0.06060606, 3.        ],
       [0.06060606, 0.09259259, 0.08219178]])

In [114]:
np.exp(1)

2.718281828459045

In [115]:
np.exp(2)

7.38905609893065

# Numpy Statistics

In [116]:
a = np.array([98,76,54,32,34,57])

In [117]:
print(np.max(a))

print(np.min(a))

98
32


In [118]:
print(np.mean(a))
print(np.median(a))
print(np.var(a))
print(np.std(a))

58.5
55.5
531.9166666666666
23.06331863949043


# Linspace


In [119]:
np.linspace(1,5,9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [120]:
## in linspace it take equal gap in betwwn the numbers

# Sorting , stacking , concatenate , Append 

In [121]:
#1 . 

In [122]:
arr = np.random.randint(40, 90, size = (5, 10))

print(arr)

[[77 48 85 59 41 82 83 76 65 47]
 [83 81 41 65 73 67 67 79 89 52]
 [67 69 77 46 63 52 54 61 51 63]
 [59 78 63 88 79 73 41 69 74 89]
 [87 51 68 54 55 40 45 75 68 70]]


In [123]:
# column sorting 

np.sort(arr , axis = 0)

array([[59, 48, 41, 46, 41, 40, 41, 61, 51, 47],
       [67, 51, 63, 54, 55, 52, 45, 69, 65, 52],
       [77, 69, 68, 59, 63, 67, 54, 75, 68, 63],
       [83, 78, 77, 65, 73, 73, 67, 76, 74, 70],
       [87, 81, 85, 88, 79, 82, 83, 79, 89, 89]])

In [124]:
# row Sorting
np.sort(arr, axis = 1)

array([[41, 47, 48, 59, 65, 76, 77, 82, 83, 85],
       [41, 52, 65, 67, 67, 73, 79, 81, 83, 89],
       [46, 51, 52, 54, 61, 63, 63, 67, 69, 77],
       [41, 59, 63, 69, 73, 74, 78, 79, 88, 89],
       [40, 45, 51, 54, 55, 68, 68, 70, 75, 87]])

In [125]:
# stack help to convert into horizantal or virtical 

In [126]:
arr1 = np.arange(20,30).reshape(2,5)
print(arr1)
arr2 = np.arange(40,50).reshape(2,5)
print(arr2)

[[20 21 22 23 24]
 [25 26 27 28 29]]
[[40 41 42 43 44]
 [45 46 47 48 49]]


In [127]:
np.vstack([arr1,arr2])

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [128]:
np.hstack([arr1,arr2])

array([[20, 21, 22, 23, 24, 40, 41, 42, 43, 44],
       [25, 26, 27, 28, 29, 45, 46, 47, 48, 49]])

In [129]:
## concatenate is adding two array in rows and colums


In [130]:
np.concatenate([arr1 , arr2],axis = 1)

array([[20, 21, 22, 23, 24, 40, 41, 42, 43, 44],
       [25, 26, 27, 28, 29, 45, 46, 47, 48, 49]])

In [131]:
np.concatenate([arr1 , arr2],axis = 0)

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [132]:
# append adding the array in the end of array


In [133]:
np.append(arr1 , arr2,axis = 1)

array([[20, 21, 22, 23, 24, 40, 41, 42, 43, 44],
       [25, 26, 27, 28, 29, 45, 46, 47, 48, 49]])

In [134]:
np.append(arr1 , arr2,axis = 0)

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])